workflows:
  build_app:
    name: "Build Application"
    environment:
      flutter: stable       # ou spécifier une version stable précise si nécessaire
      xcode: latest         # utilise la dernière version Xcode disponible sur Codemagic
    scripts:
      - name: 📦 Install dependencies
        script: |
          flutter pub get
      - name: 🛠 Build Android release
        script: |
          flutter build apk --release
      - name: 🛠 Build iOS IPA
        script: |
          flutter build ipa --release
    artifacts:
      - build/app/outputs/flutter-apk/app-release.apk
      - build/ios/ipa/*.ipa
