name: ai_prospect_gps
description: "Application Prospection GPS du Kit Commercial"
publish_to: 'none'

version: 1.0.0+14



environment:
  sdk: ">=3.3.0 <4.0.0"


dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  firebase_core: ^3.13.0
  cloud_firestore: ^5.6.7
  firebase_auth: ^5.5.3
  google_maps_flutter: ^2.10.1
  location: ^7.0.1
  intl: ^0.20.2
  flutter_screenutil: ^5.9.3
  google_sign_in: ^6.2.2
  flutter_svg: ^2.1.0
  shared_preferences: ^2.5.3
  firebase_messaging: ^15.2.5
  easy_localization: ^3.0.7+1
  http: ^1.3.0
  share_plus: ^11.0.0
  url_launcher: ^6.3.1
  auto_size_text: ^3.0.0
  provider: ^6.1.5
  qr_flutter: ^4.1.0
  flutter_html: ^3.0.0-beta.2
  flutter_launcher_icons: ^0.14.3
  google_mobile_ads: ^5.3.1
  fl_chart: ^0.66.0
  firebase_storage: ^12.4.5
  sign_in_with_apple: ^6.1.0
  crypto: ^3.0.3



dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/icons/Google.svg
    - assets/images/logo.png
    - assets/images/united-kingdom.png
    - assets/images/france.png
    - assets/translations/fr.json
    - assets/translations/en.json
    - assets/images/rgpd.jpeg
    - assets/images/backgroundlogin.jpg
    - assets/icons/planifier.png
    - assets/icons/carte.png
    - assets/icons/report.png
    - assets/icons/historique.png
    - assets/icons/parametres.png
flutter_launcher_icons:
  android: true
  ios: true
  remove_alpha_ios: true
  image_path_android: assets/app_icons/prospecto.png       # ou prospecto / simeo
  image_path_ios:     assets/app_icons/prospecto.png
